- name: zamp-banking-svc
  namespace: zamp
- name: zamp-banking-payment-consumer
  namespace: zamp
- name: zamp-banking-web3communicator-consumer
  namespace: zamp
- name: zamp-banking-view-consumer
  namespace: zamp
- name: zamp-banking-payout-consumer
  namespace: zamp
- name: zamp-banking-payout-view-consumer
  namespace: zamp
- name: zamp-banking-order-consumer
  namespace: zamp
- name: zamp-banking-crypto-exchanger
  namespace: zamp
- name: zamp-banking-damac-destination-assets
  namespace: zamp
- name: zamp-banking-probo-destination-assets
  namespace: zamp
- name: zamp-banking-merchant-ephemeral-wallet-pool
  namespace: zamp
- name: zamp-banking-probo-ephemeral-wallet-pool
  namespace: zamp
- name: zamp-banking-damac-ephemeral-wallet-pool
  namespace: zamp
- name: zamp-banking-high-priority-notifications-consumer
  namespace: zamp
- name: zamp-banking-investment-asset-loading-job
  namespace: zamp
- name: zamp-banking-ops-merchant-creation-job
  namespace: zamp
- name: zamp-banking-ops-acceptance-onboarding-job
  namespace: zamp
- name: zamp-banking-operations-consumer
  namespace: zamp
- name: zamp-banking-cards-consumer
  namespace: zamp
- name: zamp-banking-cards-trx-settlement-polling-job
  namespace: zamp
- name: zamp-banking-dashboard-home-page-computer-consumer
  namespace: zamp
- name: zamp-banking-exchange-rate-display-job
  namespace: zamp
- name: zamp-banking-ledger-recon-job
  namespace: zamp
- name: zamp-banking-erp-consumer
  namespace: zamp
- name: zamp-banking-merchant-product-intent-migration-job
  namespace: zamp
- name: zamp-banking-reports-consumer
  namespace: zamp
- name: zamp-banking-merchant-aum-calculation-job
  namespace: zamp
- name: zamp-banking-bulk-payout-data-update-job
  namespace: zamp
- name: zamp-banking-default-roles-migration-job
  namespace: zamp
- name: zamp-banking-tms-payout-request-consumer
  namespace: zamp
- name: zamp-banking-process-transaction-requests-job
  namespace: zamp
- name: zamp-banking-liquidity-monitoring-job
  namespace: zamp
- name: zamp-banking-cash-ops-bank-transactions-ladder-job
  namespace: zamp
- name: zamp-banking-cash-ops-balance-analytics-job
  namespace: zamp
- name: zamp-banking-bulk-action-status-tracker-job
  namespace: zamp
- name: zamp-banking-add-pdf-extension-in-reports-job
  namespace: zamp
- name: zamp-banking-generic-events-consumer
  namespace: zamp
- name: zamp-banking-audit-logs-consumer
  namespace: zamp
- name: zamp-banking-internal-transfer-consumer
  namespace: zamp
- name: zamp-banking-compute-hourly-analytics-job
  namespace: zamp
- name: zamp-banking-cash-ops-txn-add-desc-job
  namespace: zamp
- name: zamp-banking-file-imports-cron-job
  namespace: zamp
- name: zamp-banking-currency-exchange-history-job
  namespace: zamp 
- name: zamp-banking-account-details-pdf-job
  namespace: zamp
- name: zamp-banking-analytics-old-data-compute-job
  namespace: zamp
- name: zamp-banking-migrate-deposit-accounts-job
  namespace: zamp
- name: zamp-banking-bulk-resource-tag-mappings-consumer
  namespace: zamp
- name: zamp-banking-chainalysis-transfer-alerts-job
  namespace: zamp
- name: zamp-banking-cash-ops-payout-policy-evaluation-job
  namespace: zamp
- name: zamp-banking-generate-banking-month-reports-job
  namespace: zamp
- name: zamp-banking-get-deposit-accounts-balances-job
  namespace: zamp
- name: zamp-banking-pg-recon-consumer
  namespace: zamp
- name: zamp-banking-reconciliation-consumer
  namespace: zamp
- name: zamp-banking-file-processing-results-consumer
  namespace: zamp
- name: zamp-banking-cache-binance-exchange-rates-job
  namespace: zamp
- name: zamp-banking-daily-forecasting-job
  namespace: zamp
- name: zamp-banking-manual-create-banking-month-reports-job
  namespace: zamp
- name: zamp-banking-compute-historical-forecasting-job
  namespace: zamp
- name: zamp-recon-svc
  namespace: recon
- name: zamp-recon-celery
  namespace: recon
- name: zamp-banking-canary-svc-canary
  namespace: zamp
- name: zamp-banking-cache-layer2-exchange-rates-job
  namespace: zamp
- name: zamp-banking-file-imports-consumer
  namespace: zamp
- name: zamp-banking-tagging-generic-events-consumer
  namespace: zamp
- name: zamp-banking-bulk-tag-update-analytics-consumer
  namespace: zamp
- name: zamp-banking-bulk-tag-update-forecast-consumer
  namespace: zamp
- name: zamp-banking-bulk-actions-consumer
  namespace: zamp
- name: zamp-banking-seed-transactions-consumer
  namespace: zamp
- name: zamp-banking-bulk-action-tasks-consumer
  namespace: zamp
- name: zamp-banking-compute-classifications-job
  namespace: zamp
- name: zamp-banking-export-data-consumer
  namespace: zamp
- name: zamp-banking-funds-in-transit-consumer
  namespace: zamp
- name: zamp-banking-funds-in-transit-historical-job
  namespace: zamp
- name: zamp-banking-hourly-forecasting-job
  namespace: zamp
- name: zamp-banking-txn-seeded-forecast-consumer
  namespace: zamp
- name: zamp-banking-tms-execute-payout-job
  namespace: zamp
- name: zamp-banking-funds-in-transit-aggregate-job
  namespace: zamp
- name: zamp-banking-update-partner-beneficiary-status-job
  namespace: zamp
- name: zamp-banking-daily-data-integrity-job
  namespace: zamp
- name: zamp-banking-fixed-deposit-processing-consumer
  namespace: zamp
- name: zamp-banking-create-entity-payout-templates-job
  namespace: zamp
- name: zamp-banking-historical-currency-exchange-job
  namespace: zamp
- name: zamp-banking-update-cashops-bank-balance-consumer
  namespace: zamp
- name: zamp-banking-cashops-balance-population-job
  namespace: zamp
- name: zamp-banking-fetch-binance-deposits-job
  namespace: zamp
- name: zamp-banking-crypto-withdraw-details-job
  namespace: zamp
- name: zamp-banking-default-balance-population-job
  namespace: zamp
- name: zamp-banking-datasheet-config-creation-job
  namespace: zamp
- name: zamp-banking-assign-roles-to-users-job
  namespace: zamp
- name: zamp-banking-datasheet-config-management-consumer
  namespace: zamp
- name: zamp-banking-windmill
  namespace: windmill
- name: zamp-banking-backfill-internal-settlement-txns-job
  namespace: zamp
- name: zamp-banking-generic-migration-job
  namespace: zamp
- name: zamp-banking-cash-ops-transactions-manual-ladder-job
  namespace: zamp
- name: zamp-banking-smb-customer-account-migration-job
  namespace: zamp
- name: zamp-banking-process-stuck-transactions-job
  namespace: zamp
- name: zamp-banking-sync-partners-balances-job
  namespace: zamp
- name: zamp-banking-data-ingestion-worker
  namespace: zamp
- name: zamp-banking-resource-metadataservice-sofr-daily
  namespace: zamp
- name: zamp-banking-sofr-historical
  namespace: zamp
- name: zamp-banking-funds-in-transit-worker
  namespace: zamp
- name: zamp-browser-automation
  namespace: zamp
- name: zamp-banking-balances-recon-job
  namespace: zamp
- name: zamp-banking-cashops-bank-balances-worker
  namespace: zamp
- name: zamp-banking-transactions-recon-job
  namespace: zamp
- name: zamp-banking-fixed-deposit-maturity-cleanup-job
  namespace: zamp
- name: zamp-banking-file-imports-worker
  namespace: zamp
- name: zamp-banking-process-stuck-events-job
  namespace: zamp
- name: zamp-banking-fetch-binance-subaccount-deposits-job
  namespace: zamp
- name: zamp-banking-payout-status-processing-worker
  namespace: zamp
- name: zamp-banking-settlement-report-job
  namespace: zamp
- name: zamp-banking-process-next-transaction-event
  namespace: zamp